apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: camb-kvstore-hpa
  namespace: camb-kvstore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: camb-kvstore-app
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 50
        periodSeconds: 10
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 2
        periodSeconds: 10
      selectPolicy: Max