apiVersion: v1
kind: Service
metadata:
  name: camb-kvstore-metrics
  namespace: camb-kvstore
  labels:
    app: camb-kvstore
    component: metrics
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: metrics
  selector:
    app: camb-kvstore
    component: api
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: camb-kvstore-monitor
  namespace: camb-kvstore
  labels:
    app: camb-kvstore
spec:
  selector:
    matchLabels:
      app: camb-kvstore
      component: metrics
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s